### ISSUE TITLE
Подскажите

### ISSUE THREAD

**Issue by krishamsword** [Toveal/jsonschema-1C#1]
Привет, Компонента супер, конечно при проверке жаль не показывает поле в котором ошибка если поле не соответствует регулярке. Но есть вопрос, а есть ли возможность, как то передать массив JSON схем? необходимость возникла из-за того что в схеме есть ссылки на другие схемы JSON. Спасибо

**Comment by krishamsword** [comment]
В принципе с несколькими схемами дополнительными разобрался, написал слияние схем в одну. Но вот поле по какому ошибка конечно очень не хватает. Планируется ли какие то доработки этой компоненты?
вот пример ошибки {"keywordLocation":"/properties/data/properties/loan/$ref","instanceLocation":"/data/loan","error":"\"\" is not one of [\"9\",\"5\",\"4\",\"3\",\"2\",\"1\"]"}, в данном случае поле должно было принять одно из значений перечисления, а оно пустое, но вот что это за поле компонента не пишет, возможно можно как то получить это поле?  я не сильно понял как работать с форматом.

**Comment by Toveal** [comment]
Привет. Доработки планируются и делаются. Этот репо больше как тестовый был сделан. Я планирую этот репо перекинуть в архив и создать новый в котором помещу доработанную компоненту с более детальной инструкцией.
В новой версии с регуляркой вывод можно получить такой (используя формат):
`"/test \"123\" does not match \"^[0-9]{4}$\""`
Примерно для такой схемы:
```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Generated schema for Root",
    "type": "object",
    "properties": {
        "test": {
           "type": "string",
           "pattern": "^[0-9]{4}$"
        }
    }
}
```
Поэтому проблема будет решена. Планирую создать новый репо сегодня или завтра. На этой неделе в общем. Так же туда пойдут дополнительные форматы (uuid, инн юр и физ лица) и другие если придут в голову. Можно будет использовать примерно так:

```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Generated schema for Root",
    "type": "object",
    "properties": {
        "inn": {
            "type": "string",
            "format": ""
        },
        "selfEmployed": {
            "type": "boolean"
        },
        "bank": {
            "type": "string",
            "pattern": "^[0-9]{9}$"
        },
        "test": {
           "type": "string",
           "pattern": "^[0-9]{4}$"
        },
        "name": {
            "type": "string"
        },
        "corrAccount": {
            "type": "string"
        },
        "currentAccount": {
            "type": "string"
        },
        "contactInfo": {
            "type": "object",
            "properties": {
                "phone": {
                    "type": "string"
                },
                "email": {
                    "type": "string",
                    "format": "email"
                },
                "legalAddress": {
                    "type": "string"
                },
                "actualAddress": {
                    "type": "string"
                }
            },
            "required": [
                "phone",
                "email",
                "legalAddress",
                "actualAddress"
            ]
        },
        "kpp": {
            "type": "string",
            "pattern": "^[0-9]{9}$"
        }
    },
    "required": [
        "inn",
        "selfEmployed",
        "bank",
        "name",
        "corrAccount",
        "currentAccount",
        "contactInfo",
        "kpp"
    ],
    "if": {
        "properties": {
            "selfEmployed": {
                "const": true
            }
        }
    },
    "then": {
        "properties": {
            "inn": {
                "type": "string",
                "format": "ru-inn-individual"
            }
        }
    },
    "else": {
        "properties": {
            "inn": {
                "type": "string",
                "format": "ru-inn-legal-entity"
            }
        }
    },
    "additionalProperties": false
}
```

**Comment by Toveal** [comment]
Что касается ссылки на другую схему, попробую добавить. Тоже закину в новую версию

**Comment by krishamsword** [comment]
Подскажите пожалуйста в каком виде должен передаваться формат, вообще не пойму, это описание полей который мне должны вернутся в случае ошибки? или в этой версии формат пока не работает? Если будет не сложно в новой версии киньте пример этого формата. Большое спасибо за ответ и за компоненту, очень спасла.

**Comment by Toveal** [comment]
Используйте формат как `СтрШаблон`. Только вместо %1 %2 и т.д. у вас доступны:

1. **{path}**
2. **{instance}**
3. **{schema_path}**

**path** - Путь до свойства в переданном json для валидации. Пример: `/user/name`
**instance** - Значение свойства, которое не прошло проверку.
**schema_path** - Путь до ключевого слова в схеме вызвало ошибку. Пример: `/properties/test/pattern`

Например:
Шаблон - `это значение {instance} неправильное в поле {path}`
Результат - `это значение "123" неправильное в поле /test`

В новой версии я доработаю описание и добавлю еще парочку шаблонов для подстановки
Спасибо за добрые слова :)

**Comment by Toveal** [comment]
У меня получилось реализовать дополнительные схемы и обработку ссылок на эти схемы из основной схемы. Ожидайте в следующей версии. Ссылку на новый репозиторий кину сюда

**Comment by krishamsword** [comment]
супер, спасибо большое!

**Comment by Toveal** [comment]
Используйте [новую версию](https://github.com/Toveal/jsonschema-1c)
